### ISSUE TITLE
Prototype - Helen's site + commons book ends

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/canada-ca.github.io#1]
@robotbotman Can you show me how to start creating my static page information architecture here? I'm going to create content to map to Helen's prototype. @laurawesley will add content too.

mb

**Comment by smellems** [comment]
Do you want to use Jekyll or just HTML?  WET?

**Comment by MaryBethBaker** [comment]
@smellems We want to use WET + something easy for publishing such as Jekyll...

**Comment by sboots** [comment]
Hey @MaryBethBaker! I have a prototype Jekyll + WET combo system in the works, it's still not perfect but it uses <https://github.com/plusjade/jekyll-bootstrap> as a starting point and brings in the WET templates. I can try to tidy up a version and put it in a new repo?

**Comment by smellems** [comment]
@sboots I also had a prototype Jekyll + WET site I had tested for the hackathon (https://smellems.github.io/).

It's also bilingual :)

It still need work to translate all the footer links and other stuff.  Hope it helps!

**Comment by MaryBethBaker** [comment]
@sboots @smellems Awesome - you two know each other right? I need to get something that uses the canada.ca theme... but I assume I just reference the different theme in my code and it will replace anything custom or different.

mv

**Comment by smellems** [comment]
The pull request is using the GCWeb (canada.ca) theme.  with the menus from CDN.
