### ISSUE TITLE
Add previous posts

### ISSUE THREAD

**Issue by lisafast** [canada-ca/canada-ca.github.io#10]
@MaryBethBaker Let's assume we are all going to blog here about our work.  Could we up the game a bit by adding a previous posts on the right or at the bottom?

- this fellow mentions that previous posts is easy and has a code snippet but I don't have a clue where to put that snippet!   https://isaacjordan.me/blog/2016/01/popular-posts-using-jekyll-github-pages/ 

Maybe @smellems does?

If that's too difficult, could just add next and previous at bottom, like this: http://david.elbe.me/jekyll/2015/06/20/how-to-link-to-next-and-previous-post-with-jekyll.html

**Comment by MaryBethBaker** [comment]
Any updates to this from @smellems or @RachelMuston ? ... another person to ask is @sboots or maybe Olivia for a Gov.uk contact... I found this example on their site. I don't see a previous posts element on 18F.gsa.gov or digital.canada.ca's blogs.

![latestblogposts_ukgov](https://user-images.githubusercontent.com/532766/29220980-f84f2a5a-7e8a-11e7-842b-98658ada4299.jpg)

Source: https://www.blog.gov.uk/

**Comment by lisafast** [comment]
Yes, exactly - that looks great. Will have to handle the French and English separately though.

**Comment by smellems** [comment]
Pretty sure this would be possible with the French English.  I will need to test it

**Comment by smellems** [comment]
I added previous and next buttons at the bottom of blog posts.

We could add a column with the latest post if that's what we want.  We just add a culumn to the right.  Do we have enough content for a new column?

**Comment by lisafast** [comment]
Thanks @smellems!    We don't have enough yet for a column, but hope to be there in about a month or so, so for now, these previous and next buttons really help. 

Would it be possible to use the existing WET/Canada.ca styles for the buttons (used in the Advanced Service Initiation template and on forms) - we found in previous research that locating the buttons on the left and right was best for users. You can see an example of this style on this Advanced Service page: 
https://www.canada.ca/en/services/benefits/ei/ei-maternity-parental/eligibility.html

**Comment by smellems** [comment]
I made the changes.  I did'nt use the right class for pager buttons.
http://wet-boew.github.io/wet-boew-styleguide/v4/design/pagination-en.html#pager

**Comment by lisafast** [comment]
This is great! One last thing we need to do is set up the 'All posts" link in the breadcrumb and somewhere else - to lead to main post page (this one: https://canada-ca.github.io/ )

For the breadcrumb, there is an important policy that you should know. If the page (anywhere, on any URL) is in Canada.ca format with the menus at the top, then Home in the breadcrumb has to lead to the home page of Canada.ca in the appropriate language - so https://www.canada.ca/en.html or https://www.canada.ca/fr.html ). Then the next item in the breadcrumb is the parent - so 'All posts" in this case. 

Possible?

**Comment by pcwsmith** [comment]
I replicated the breadcrumbs q as a separate issue - #14

Cuz I think we should actually pursue the previous posts lists on the right rail sooner rather than later. Only been fiddling around with this for a week or so and we already have three drafts on the fly, so really won't be long until we need it for reals. thx

**Comment by lisafast** [comment]
Instead of right rail, would really prefer at the bottom. That's the new style (see CDS blog Medium, Linked in blogs), because it encourages reading/focus ON the article in this age of low attention spans. Right column narrows the article, can drag eyes over and distract.  

I was going to suggest snitching the code from the [CDS Blog](https://digital.canada.ca/2017/07/28/think-big-start-small/), also in this  Canada-ca repo, but right now, they only have "previous post" and "next post" links at the bottom, so we are already past that with the great work @smellems did with the post titles in those buttons.

**Comment by pcwsmith** [comment]
sure good point, let's put it at the bottom.

my thinking on right rail was actually just to help shorten the line length for the articles since the full width layout is really wiiiide, but that's definitely a lesser evil than distracting with extra links and stuff beside the article. thx
