### ISSUE TITLE
French and English posts

### ISSUE THREAD

**Issue by smellems** [canada-ca/canada-ca.github.io#12]
For the site to work correctly it's important to create post in French and English at the same time.  The files can be empty but have a correct [Front Matter](https://jekyllrb.com/docs/frontmatter/).

The `ref` and `lang` parameters are important.

`ref` is what links the translations, it need to be the same for the French and English versions of posts as well as unique to the site.  You can't have two posts with the same `ref`.

There is currently a bug because the Test blog is using the same `ref` as the Welcome to Jekyll blog.

Also, if there is no French version of the post, the link to change language does not show in the top right.

**Comment by smellems** [comment]
I changed the `ref` for the test post to test and that fixed the issue : when in French, on the Welcome to Jekyll blog, there were 2 links at the top right that both said English, one to test and the other to Welcome..

Now that works, but since the last 2 blogs don't have a French versions, the previous next buttons don't all show up in French to those articles

**Comment by lisafast** [comment]
Thanks for this @smellems , we are working out the French versions - will translate soon.
