### ISSUE TITLE
where is the _drafts folder?

### ISSUE THREAD

**Issue by pcwsmith** [canada-ca/canada-ca.github.io#13]
Right now we're doing drafts of posts in the main _posts folder. Was thinking about how to manage this moving forward and it looks like the best answer is a _drafts folder: https://jekyllrb.com/docs/drafts/

But I don't actually see the drafts folder in the repository.  How do I create this?

**Comment by smellems** [comment]
From what I can see, we could just create a `_drafts` folder and put post in there.

I like the idea.  You will have to test your posts locally using `jekyll serve --drafts`.

Also not sure how it will work with the French English..  We should try it

**Comment by pcwsmith** [comment]
I dunno actually what testing locally w `jekyll serve --drafts` means?

**Comment by smellems** [comment]
I added the `_drafts` folder and moved the test post to it.  The test post no longer appears on the site.

Not sure if this works for you.  You can still work on them on Github, and use the Preview to get an idea of what the post will look like and then move it to the `_posts` folder once it's ready.

To see it you have to build the site locally using Jekyll.  https://jekyllrb.com/docs/usage/
And you would also have to use Git to save your changes to Github.

**Comment by pcwsmith** [comment]
oooooh we cant use Git here at work (IT restrictions), but maybe we can still make use of this to manage writing before publishing. will check it out further & report back. Thx

**Comment by pcwsmith** [comment]
ok we've got ourselves set up to use the drafts folder, so closing this issue

**Comment by MaryBethBaker** [comment]
@smellems Has a request been put into the departmental IT to ask for permission to use Git? I have a Windows Git CMD on my workstation here.

**Comment by pcwsmith** [comment]
@MaryBethBaker we're just using the web interface, so can't actually preview drafts, but seems to work ok for now
