### ISSUE TITLE
set up breadcrumb

### ISSUE THREAD

**Issue by pcwsmith** [canada-ca/canada-ca.github.io#14]
extracting this from: https://github.com/canada-ca/canada-ca.github.io/issues/10#issuecomment-322504715

> set up the 'All posts" link in the breadcrumb and somewhere else - to lead to main post page (this one: https://canada-ca.github.io/ )
> 
> For the breadcrumb, there is an important policy that you should know. If the page (anywhere, on any URL) is in Canada.ca format with the menus at the top, then Home in the breadcrumb has to lead to the home page of Canada.ca in the appropriate language - so https://www.canada.ca/en.html or https://www.canada.ca/fr.html ). Then the next item in the breadcrumb is the parent - so 'All posts" in this case.
> 

Possible?

**Comment by smellems** [comment]
This is definitely possible

**Comment by pcwsmith** [comment]
great @smellems thx! Can you make it happen? I have no idea how.
