### ISSUE TITLE
GC Task navigation

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/canada-ca.github.io#3]
Task navigation isn't working.  @smellems can you help us?

**Comment by smellems** [comment]
We need to change the CDN from http to https.  I will try and fix it soon

**Comment by MaryBethBaker** [comment]
Thanks @smellems. @RachelMuston and I are learning how to use Jeykll so we can prepare a library of collaboration tools and other elements for projects. Thanks for making the WET + Jeykll site for us! 💯
