### ISSUE TITLE
Better description please.

### ISSUE THREAD

**Issue by mgifford** [canada-ca/canada-ca.github.io#31]
This isn't a good description for this project " Github pages for the Canada.ca product blog "

I'm also not sure if this is live https://canada-ca.github.io/

Does it tie into http://open.canada.ca/en/blog

What blogs are being published in the GoC? 

Maybe this is just a prototyping space?

**Comment by patlaj** [comment]
Hey Mike - thanks, good point. I'm going to get that description updated to be more helpful. 

It's not (supposed to be) live, we're just working on it now. We have a ways to before it'll be launchable. (It's mostly going to be a place to share evidence and info about the design of Canada.ca, so we can associate the "why" with the guidance.) 

The Open Gov blog is specific to open government topics, so we wouldn't tie in with that. 

@mgifford

**Comment by mgifford** [comment]
Thanks! So often the descriptions are too vague to know how if they are of interest. 

Appreciate the explanation. 

Mike

**Comment by patlaj** [comment]
Updated now, thanks again Mike.
