### ISSUE TITLE
Better alt text

### ISSUE THREAD

**Issue by mgifford** [canada-ca/canada-ca.github.io#33]
There is alt text for the graph here, but it needs a better description:
https://canada-ca.github.io/category/2017/12/12/optimization-overview.html

The image is essentially described in the text below it, but there isn't a semantic relationship between the two. figure/figcaption could be used to do this.

aria-describedby could also be used to build an association.

**Comment by patlaj** [comment]
Thanks for this Mike - we updated the alt text to refer to the details following, and used figure/figcaption to establish the relationship.
