### ISSUE TITLE
Odd left/right arrow key behavior in menubar

### ISSUE THREAD

**Issue by carmacleod** [canada-ca/canada-ca.github.io#34]
Issue part 1:

1. Go to https://www.canada.ca/en.html
2. Using only the keyboard, navigate to the menubar; the Jobs menu opens
3. Type right arrow; the Immigration menu opens
4. Type down arrow a couple of times; you are on the Visit menuitem
5. Now type right arrow

The expected behavior is that the menu to the right (the Travel menu) would open.
Instead, surprisingly, the Jobs menu (the one on the left) opens.

Issue part 2:

1. Repeat steps 1 - 4, above
2. Now type left arrow

The expected behavior is that the menu to the left (the Jobs menu) would open.
Instead, quite surprisingly, the Taxes menu (way over on the right) opens.

**Comment by lisafast** [comment]
@carmacleod Would it be possible for you to repost it to the developer-operations issues site for Canada.ca? It's at: https://github.com/wet-boew/GCWeb/issues  (I wish I could move the issue there for you, but the ability to move or clone issues is not built into Github). 

This repository is for the Canada.ca design and prototyping team. We don't have access to the code that would control issues like the important one you have posted. 

Thanks very much!

**Comment by carmacleod** [comment]
Ok, @lisafast - done!
Sorry about that, and thanks for the redirect.  :)
I'll close this issue.
