### ISSUE TITLE
"Report a problem or mistake on this page" form is not useful

### ISSUE THREAD

**Issue by carmacleod** [canada-ca/canada-ca.github.io#35]
To see the "Report a problem or mistake on this page" form in action:
- Go to [canada.ca](https://www.canada.ca/en.html)
- Imagine that you notice an issue on the page that, as a good web citizen, you want to report
- Look for, and finally find the "Report a problem or mistake on this page" button (aside: it is hard to find because it is not in the page footer. It is hiding above the "Government of Canada activities and initiatives" content).
- Click the "Report a problem or mistake on this page" button to reveal the "Please select all that apply" checkboxes (see first screen snap)
- Select "Something is broken" and then Submit

![screen snap of "Report a problem" form](https://user-images.githubusercontent.com/3331913/37614429-1b0f05bc-2b81-11e8-9109-301d691b3153.png)

At this point, the user expects to be able to type in the problem detail, i.e.:
_What_ is broken? _What_ is the spelling or grammar mistake? _What_ information is wrong or outdated?

The user can provide this information, because that is why they clicked on "Report a problem or mistake on this page". And yet, all I got was "Thank you for your help!" (see second screen snap)

![image](https://user-images.githubusercontent.com/3331913/37614792-05ef003c-2b82-11e8-8e40-e8b79e826e4a.png)

This is not useful. I had to guess that maybe canada.ca had a github presence. Luckily you do, so I was able to report my problem anyhow (issue #34). However, the current "Report a Problem" form must be quite frustrating for those who don't know to try searching github. (I tried it about 6 times before giving up and trying github. If I didn't know about github, you would not have heard from me).

**Comment by lisafast** [comment]
@carmacleod We're sorry you had this problem. The Report a problem button used to work exactly the way you state above - a field was provided into which the problem reporter could type the problem details. Again, I do wish I could copy the issue for you but since I cannot, could you please post the issue on the repo that the developers and operations team for Canada.ca manage? It is here: https://github.com/wet-boew/GCWeb/issues

**Comment by carmacleod** [comment]
No worries, @lisafast - done.  :)
Thanks again!
