### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/canada-ca.github.io#38]
Quick question: Are there a set of instructions somewhere that you used for adding the WET templates? I'm working on the Communicating Public Engagement gh-pages, but I don't know how to get the theme and page structure up.

Thanks!
mb

/cc @nschonni @lisafast @jmealing

**Comment by nschonni** [comment]
Maybe check out #36 since @pjackson28 took this stuff, then used the CDTS stuff on top
I've got it in my personal backlog to try and get the Jekyll theme working like the USWDS one

**Comment by pjackson28** [comment]
@MaryBethBaker The key files can be found in https://github.com/canada-ca/digital-playbook-guide-numerique and they are:

- _includes/head.html
- _includes/header.html
- _includes/footer.html
- _layouts/default.html
- _config.yml
- YAML front matter in each of the .md files (used for layout, h1/title and language links)
- 404.html and index.html are the 404 error and splash pages respectively

Those should have all the Canada.ca theme markup and strings. All the CSS, JS, image and other files are pulled remotely from CDTS (so not stored locally). In the files with the markup there may be some extra stuff that is Digital Playbook-specific that you may want to take out (or can reuse if you like) like the pagination.

**Comment by MaryBethBaker** [comment]
Archiving issue.
