### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by lisafast** [canada-ca/canada-ca.github.io#7]
@RachelMuston - we put some images into our post on this blog site. Two questions: 

1. We created a folder at the Posts level for images - does that fit your model of how the posts should work - or should each dated post have its own folder? Since this is your repo, thought I better ask! 
2. We can't get the images to actually show up online - they show up in the preview so clearly the referencing is right there, but once it actually posts, they are broken (actually, it is weirder than that, they used to show up as broken link images, but now they just dont show up at all - there is nothing there at all depending on what browser you use.)
Thanks, Lisa 

PS We are still just testing whether to post articles about Canada.ca usability and design here. Not fully decided but seemed like a good place since we all have github accounts and are prototyping the designs in Github.  We want to post somewhere where the team and really anyone working on improving online service on Canada.ca can all contribute articles rather than somewhere individual-oriented like Linked In or Medium. 
@laurawesley thoughts?

**Comment by RachelMuston** [comment]
Hi Lisa, 
Good questions!  I don't have the answer yet but will investigate.  :-)  @MaryBethBaker may also have some thoughts esp. re: folder structure.

Like you, Laura's group is also in test mode re: whether this is the best place to blog.  We were looking for the same thing -  a place for the team to blog as opposed to a single individual.  One question we had about this platform was what are the capacity limits of GitHub hosting?
